version: '3.9'

services:
  database:
    container_name: frontendmentor_database
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: entertainment-app
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend
    ports:
      - '5432:5432'
    volumes:
      - backend-database:/var/lib/postgresql/data

volumes:
  backend-database:
